In [ ]:
import numpy as np
arr = np . arange (0 , 10 , 1)

In [3]:
import numpy as np
arr = np.full((3, 3), fill_value = True, dtype = bool )

In [4]:
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [5]:
import numpy as np
arr = np.arange (0 ,10)
print(arr [ arr %2 == 1])

[1 3 5 7 9]


In [7]:
import numpy as np
arr = np.arange (0 ,10)
arr[arr%2 ==1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [8]:
import numpy as np
arr = np.arange(10)
arr_2d = arr.reshape(2, -1)
print (arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [9]:
import numpy as np
arr1 = np.arange(10).reshape (2, -1)
arr2 = np.repeat(1,10).reshape (2, -1)
c = np . concatenate ([ arr1 , arr2 ], axis =0)
print (" Result : \n", c )

 Result : 
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [10]:
import numpy as np
arr1 = np.arange (10).reshape (2 , -1)
arr2 = np.repeat (1 ,10).reshape (2 , -1)
c = np.concatenate ([ arr1 , arr2 ], axis =1)
print ("C = ", c )

C =  [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [ ]:
import numpy as np
arr = np.array ([1,2,3])
print (np.repeat (arr ,3) )
print (np.tile (arr, 3) )

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


In [ ]:
import numpy as np
a = np.array([2, 6, 1, 9, 10, 3, 27])
index = (a>=5) & (a<=10)
print("result ", a[index])

result  [ 6  9 10]


In [13]:
import numpy as np
def maxx (x , y ) :
  if x >= y :
    return x
  else :
    return y

a = np.array ([5 ,7 ,9 ,8 ,6 ,4 ,5])
b = np.array ([6 ,3 ,4 ,8 ,9 ,7 ,1])

pair_max = np.vectorize (maxx, otypes =[float ])
print(pair_max(a, b ) )

[6. 7. 9. 8. 9. 7. 5.]


In [14]:
import numpy as np

a = np.array ([5 ,7 ,9 ,8 ,6 ,4 ,5])
b = np.array ([6 ,3 ,4 ,8 ,9 ,7 ,1])

print("Result ", np.where (a <b, b, a))

Result  [6 7 9 8 9 7 5]


In [ ]:
! gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB

import matplotlib.image as mpimg
img = mpimg.imread ('dog.jpeg')

# Your Code Here
gray_img_01 = (np.max(img, axis = 2) + np.min(img, axis=2)) / 2
gray_img_01 [0 , 0]

Downloading...
From: https://drive.google.com/uc?id=1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
To: /content/dog.jpeg
100% 33.7k/33.7k [00:00<00:00, 63.1MB/s]


102.5

In [27]:
# Download image
! gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB

import matplotlib.image as mpimg
img = mpimg.imread('.\dog.jpeg')
# Your Code Here
gray_img_02 = np.mean(img, axis = 2)
gray_img_02 [0, 0]

Downloading...
From: https://drive.google.com/uc?id=1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
To: /content/dog.jpeg
100% 33.7k/33.7k [00:00<00:00, 58.1MB/s]


107.66666666666667

In [29]:
# Download image
! gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB

import matplotlib.image as mpimg
img = mpimg.imread ('.\dog.jpeg')
# Your Code Here
gray_img_03 = 0.21 * img[:, :, 0] + 0.72 * img[:, :, 1] + 0.07 * img[:, :, 2]
gray_img_03 [0 , 0]

Downloading...
From: https://drive.google.com/uc?id=1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
To: /content/dog.jpeg
100% 33.7k/33.7k [00:00<00:00, 61.7MB/s]


126.22999999999999

In [38]:
# Download data
! gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
import pandas as pd
df = pd.read_csv ('\advertising.csv')
data = df.to_numpy()
sales = data[:, -1]

max_value = np.max(sales)
max_index = np.argmax(sales)

(max_value, max_index)

Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: /content/advertising.csv
100% 4.06k/4.06k [00:00<00:00, 11.5MB/s]


(27.0, 175)

In [40]:
# Download data
! gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
import pandas as pd
df = pd.read_csv ('advertising.csv')
data = df.to_numpy()
tvs = data[:, 0]

mean_value = np.mean(tvs)
print(mean_value)

Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: /content/advertising.csv
100% 4.06k/4.06k [00:00<00:00, 14.0MB/s]
147.0425


In [45]:
# Download data
! gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
import pandas as pd
df = pd.read_csv ('advertising.csv')
data = df.to_numpy()
sales = data[:, -1]
count_value = np.sum(sales >=20)
print(count_value )

Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: /content/advertising.csv
100% 4.06k/4.06k [00:00<00:00, 12.2MB/s]
40


In [46]:
# Download data
! gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
import pandas as pd
df = pd.read_csv ('./advertising.csv')
data = df.to_numpy()
sales = data[:, -1]
radio = data[:, 1]
value = sales >=15
g_radio= radio[value]
mean_radio = np.mean(g_radio)
print(mean_radio)

Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: /content/advertising.csv
100% 4.06k/4.06k [00:00<00:00, 10.0MB/s]
26.22293577981651


In [48]:
# Download data
! gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
import pandas as pd
df = pd.read_csv ('./advertising.csv')
data = df.to_numpy()

sales = data[:, -1]
newspaper = data[:, 2]
value = newspaper >np.mean(newspaper)
g_sales= sales[value]
sum_radio = np.sum(g_sales)
print(sum_radio)

Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: /content/advertising.csv
100% 4.06k/4.06k [00:00<00:00, 15.7MB/s]
1405.1


In [49]:
# Download data
!gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq

import pandas as pd
import numpy as np
df = pd.read_csv('.\advertising.csv')
data = df.to_numpy()

sales = data[:, -1]

A = np.mean(sales)

scores = np.where(sales > A, 'Good', np.where(sales < A, 'Bad', 'Average'))

print(scores[7:10])

Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: /content/advertising.csv
100% 4.06k/4.06k [00:00<00:00, 14.3MB/s]
['Bad' 'Bad' 'Good']


In [54]:
import pandas as pd
import numpy as np
df = pd.read_csv('.\advertising.csv')
data = df.to_numpy()

sales = data[:, -1]

B = np.mean(sales)
A = sales[np.abs(sales - B).argmin()]

scores = np.where(sales > A, 'Good', np.where(sales < A, 'Bad', 'Average'))

print(scores[7:10])

['Bad' 'Bad' 'Good']
